coordinate_x = int(input())
coordinate_y = int(input())
print("First possible position X: %s, Y: %s" % (coordinate_x + 1, coordinate_y + 2))
print("Second possible position X: %s, Y: %s" % (coordinate_x - 1, coordinate_y - 2))
print("Third possible position X: %s, Y: %s" % (coordinate_x + 2, coordinate_y + 1))
print("Fourth possible position X: %s, Y: %s" % (coordinate_x - 2, coordinate_y - 1))
print("Fifth possible position X: %s, Y: %s" % (coordinate_x + 1, coordinate_y - 2))
print("Sixth possible position X: %s, Y: %s" % (coordinate_x + 2, coordinate_y - 1))
print("Seventh possible position X: %s, Y: %s" % (coordinate_x - 1, coordinate_y + 2))
print("Eighth possible position X: %s, Y: %s" % (coordinate_x - 2, coordinate_y + 1))